# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: copilot.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'copilot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcopilot.proto\x12\x07\x63opilot\"\x1d\n\x0cQueryRequest\x12\r\n\x05query\x18\x01 \x01(\t\"/\n\x0b\x41nswerReply\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x10\n\x08\x63ontexts\x18\x02 \x03(\t2=\n\x07\x43opilot\x12\x32\n\x03Run\x12\x15.copilot.QueryRequest\x1a\x14.copilot.AnswerReplyB0Z.github.com/gyx22-12/vllm-copilot/gateway/pb;pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'copilot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z.github.com/gyx22-12/vllm-copilot/gateway/pb;pb'
  _globals['_QUERYREQUEST']._serialized_start=26
  _globals['_QUERYREQUEST']._serialized_end=55
  _globals['_ANSWERREPLY']._serialized_start=57
  _globals['_ANSWERREPLY']._serialized_end=104
  _globals['_COPILOT']._serialized_start=106
  _globals['_COPILOT']._serialized_end=167
# @@protoc_insertion_point(module_scope)
