# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import copilot_pb2 as copilot__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in copilot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CopilotStub:
    """Copilot 是 vLLM 工程问答的核心服务：Python 侧做检索 + ReAct 推理（脑），
    Go 网关通过 gRPC 调用它（壳）。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Run = channel.unary_unary(
                '/copilot.Copilot/Run',
                request_serializer=copilot__pb2.QueryRequest.SerializeToString,
                response_deserializer=copilot__pb2.AnswerReply.FromString,
                _registered_method=True)


class CopilotServicer:
    """Copilot 是 vLLM 工程问答的核心服务：Python 侧做检索 + ReAct 推理（脑），
    Go 网关通过 gRPC 调用它（壳）。
    """

    def Run(self, request, context):
        """Run 执行一次问答：query 进，answer + 出处 contexts 出。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CopilotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Run': grpc.unary_unary_rpc_method_handler(
                    servicer.Run,
                    request_deserializer=copilot__pb2.QueryRequest.FromString,
                    response_serializer=copilot__pb2.AnswerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'copilot.Copilot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('copilot.Copilot', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Copilot:
    """Copilot 是 vLLM 工程问答的核心服务：Python 侧做检索 + ReAct 推理（脑），
    Go 网关通过 gRPC 调用它（壳）。
    """

    @staticmethod
    def Run(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/copilot.Copilot/Run',
            copilot__pb2.QueryRequest.SerializeToString,
            copilot__pb2.AnswerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
