// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.12.4
// source: copilot.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Copilot_Run_FullMethodName         = "/copilot.Copilot/Run"
	Copilot_Suggestions_FullMethodName = "/copilot.Copilot/Suggestions"
)

// CopilotClient is the client API for Copilot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Copilot 是 vLLM 工程问答的核心服务：Python 侧做检索 + ReAct 推理（脑），
// Go 网关通过 gRPC 调用它（壳）。
type CopilotClient interface {
	// Run 执行一次问答：query 进，answer + 出处 contexts 出。
	Run(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AnswerReply, error)
	// Suggestions 返回建议问题（取自评测集随机抽样，供前端「试试这些问题」）。
	Suggestions(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsReply, error)
}

type copilotClient struct {
	cc grpc.ClientConnInterface
}

func NewCopilotClient(cc grpc.ClientConnInterface) CopilotClient {
	return &copilotClient{cc}
}

func (c *copilotClient) Run(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*AnswerReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnswerReply)
	err := c.cc.Invoke(ctx, Copilot_Run_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *copilotClient) Suggestions(ctx context.Context, in *SuggestionsRequest, opts ...grpc.CallOption) (*SuggestionsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestionsReply)
	err := c.cc.Invoke(ctx, Copilot_Suggestions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CopilotServer is the server API for Copilot service.
// All implementations must embed UnimplementedCopilotServer
// for forward compatibility.
//
// Copilot 是 vLLM 工程问答的核心服务：Python 侧做检索 + ReAct 推理（脑），
// Go 网关通过 gRPC 调用它（壳）。
type CopilotServer interface {
	// Run 执行一次问答：query 进，answer + 出处 contexts 出。
	Run(context.Context, *QueryRequest) (*AnswerReply, error)
	// Suggestions 返回建议问题（取自评测集随机抽样，供前端「试试这些问题」）。
	Suggestions(context.Context, *SuggestionsRequest) (*SuggestionsReply, error)
	mustEmbedUnimplementedCopilotServer()
}

// UnimplementedCopilotServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCopilotServer struct{}

func (UnimplementedCopilotServer) Run(context.Context, *QueryRequest) (*AnswerReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedCopilotServer) Suggestions(context.Context, *SuggestionsRequest) (*SuggestionsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Suggestions not implemented")
}
func (UnimplementedCopilotServer) mustEmbedUnimplementedCopilotServer() {}
func (UnimplementedCopilotServer) testEmbeddedByValue()                 {}

// UnsafeCopilotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CopilotServer will
// result in compilation errors.
type UnsafeCopilotServer interface {
	mustEmbedUnimplementedCopilotServer()
}

func RegisterCopilotServer(s grpc.ServiceRegistrar, srv CopilotServer) {
	// If the following call panics, it indicates UnimplementedCopilotServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Copilot_ServiceDesc, srv)
}

func _Copilot_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopilotServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Copilot_Run_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopilotServer).Run(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Copilot_Suggestions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CopilotServer).Suggestions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Copilot_Suggestions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CopilotServer).Suggestions(ctx, req.(*SuggestionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Copilot_ServiceDesc is the grpc.ServiceDesc for Copilot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Copilot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "copilot.Copilot",
	HandlerType: (*CopilotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Copilot_Run_Handler,
		},
		{
			MethodName: "Suggestions",
			Handler:    _Copilot_Suggestions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "copilot.proto",
}
