// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: copilot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_copilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_copilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_copilot_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type AnswerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`     // 最终答案
	Contexts      []string               `protobuf:"bytes,2,rep,name=contexts,proto3" json:"contexts,omitempty"` // 检索到的上下文（用于忠实度评估）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerReply) Reset() {
	*x = AnswerReply{}
	mi := &file_copilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerReply) ProtoMessage() {}

func (x *AnswerReply) ProtoReflect() protoreflect.Message {
	mi := &file_copilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerReply.ProtoReflect.Descriptor instead.
func (*AnswerReply) Descriptor() ([]byte, []int) {
	return file_copilot_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerReply) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AnswerReply) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

var File_copilot_proto protoreflect.FileDescriptor

const file_copilot_proto_rawDesc = "" +
	"\n" +
	"\rcopilot.proto\x12\acopilot\"$\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"A\n" +
	"\vAnswerReply\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1a\n" +
	"\bcontexts\x18\x02 \x03(\tR\bcontexts2=\n" +
	"\aCopilot\x122\n" +
	"\x03Run\x12\x15.copilot.QueryRequest\x1a\x14.copilot.AnswerReplyB0Z.github.com/gyx22-12/vllm-copilot/gateway/pb;pbb\x06proto3"

var (
	file_copilot_proto_rawDescOnce sync.Once
	file_copilot_proto_rawDescData []byte
)

func file_copilot_proto_rawDescGZIP() []byte {
	file_copilot_proto_rawDescOnce.Do(func() {
		file_copilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_copilot_proto_rawDesc), len(file_copilot_proto_rawDesc)))
	})
	return file_copilot_proto_rawDescData
}

var file_copilot_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_copilot_proto_goTypes = []any{
	(*QueryRequest)(nil), // 0: copilot.QueryRequest
	(*AnswerReply)(nil),  // 1: copilot.AnswerReply
}
var file_copilot_proto_depIdxs = []int32{
	0, // 0: copilot.Copilot.Run:input_type -> copilot.QueryRequest
	1, // 1: copilot.Copilot.Run:output_type -> copilot.AnswerReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_copilot_proto_init() }
func file_copilot_proto_init() {
	if File_copilot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_copilot_proto_rawDesc), len(file_copilot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_copilot_proto_goTypes,
		DependencyIndexes: file_copilot_proto_depIdxs,
		MessageInfos:      file_copilot_proto_msgTypes,
	}.Build()
	File_copilot_proto = out.File
	file_copilot_proto_goTypes = nil
	file_copilot_proto_depIdxs = nil
}
