// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.12.4
// source: copilot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_copilot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_copilot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_copilot_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type AnswerReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Answer        string                 `protobuf:"bytes,1,opt,name=answer,proto3" json:"answer,omitempty"`     // 最终答案
	Contexts      []string               `protobuf:"bytes,2,rep,name=contexts,proto3" json:"contexts,omitempty"` // 检索到的上下文（用于忠实度评估）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnswerReply) Reset() {
	*x = AnswerReply{}
	mi := &file_copilot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnswerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnswerReply) ProtoMessage() {}

func (x *AnswerReply) ProtoReflect() protoreflect.Message {
	mi := &file_copilot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnswerReply.ProtoReflect.Descriptor instead.
func (*AnswerReply) Descriptor() ([]byte, []int) {
	return file_copilot_proto_rawDescGZIP(), []int{1}
}

func (x *AnswerReply) GetAnswer() string {
	if x != nil {
		return x.Answer
	}
	return ""
}

func (x *AnswerReply) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

type SuggestionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsRequest) Reset() {
	*x = SuggestionsRequest{}
	mi := &file_copilot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsRequest) ProtoMessage() {}

func (x *SuggestionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_copilot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsRequest.ProtoReflect.Descriptor instead.
func (*SuggestionsRequest) Descriptor() ([]byte, []int) {
	return file_copilot_proto_rawDescGZIP(), []int{2}
}

type Suggestion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"` // doc / code / gen
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Suggestion) Reset() {
	*x = Suggestion{}
	mi := &file_copilot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Suggestion) ProtoMessage() {}

func (x *Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_copilot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Suggestion.ProtoReflect.Descriptor instead.
func (*Suggestion) Descriptor() ([]byte, []int) {
	return file_copilot_proto_rawDescGZIP(), []int{3}
}

func (x *Suggestion) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Suggestion) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SuggestionsReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suggestions   []*Suggestion          `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestionsReply) Reset() {
	*x = SuggestionsReply{}
	mi := &file_copilot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestionsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestionsReply) ProtoMessage() {}

func (x *SuggestionsReply) ProtoReflect() protoreflect.Message {
	mi := &file_copilot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestionsReply.ProtoReflect.Descriptor instead.
func (*SuggestionsReply) Descriptor() ([]byte, []int) {
	return file_copilot_proto_rawDescGZIP(), []int{4}
}

func (x *SuggestionsReply) GetSuggestions() []*Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

var File_copilot_proto protoreflect.FileDescriptor

const file_copilot_proto_rawDesc = "" +
	"\n" +
	"\rcopilot.proto\x12\acopilot\"$\n" +
	"\fQueryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"A\n" +
	"\vAnswerReply\x12\x16\n" +
	"\x06answer\x18\x01 \x01(\tR\x06answer\x12\x1a\n" +
	"\bcontexts\x18\x02 \x03(\tR\bcontexts\"\x14\n" +
	"\x12SuggestionsRequest\"<\n" +
	"\n" +
	"Suggestion\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"I\n" +
	"\x10SuggestionsReply\x125\n" +
	"\vsuggestions\x18\x01 \x03(\v2\x13.copilot.SuggestionR\vsuggestions2\x84\x01\n" +
	"\aCopilot\x122\n" +
	"\x03Run\x12\x15.copilot.QueryRequest\x1a\x14.copilot.AnswerReply\x12E\n" +
	"\vSuggestions\x12\x1b.copilot.SuggestionsRequest\x1a\x19.copilot.SuggestionsReplyB0Z.github.com/gyx22-12/vllm-copilot/gateway/pb;pbb\x06proto3"

var (
	file_copilot_proto_rawDescOnce sync.Once
	file_copilot_proto_rawDescData []byte
)

func file_copilot_proto_rawDescGZIP() []byte {
	file_copilot_proto_rawDescOnce.Do(func() {
		file_copilot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_copilot_proto_rawDesc), len(file_copilot_proto_rawDesc)))
	})
	return file_copilot_proto_rawDescData
}

var file_copilot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_copilot_proto_goTypes = []any{
	(*QueryRequest)(nil),       // 0: copilot.QueryRequest
	(*AnswerReply)(nil),        // 1: copilot.AnswerReply
	(*SuggestionsRequest)(nil), // 2: copilot.SuggestionsRequest
	(*Suggestion)(nil),         // 3: copilot.Suggestion
	(*SuggestionsReply)(nil),   // 4: copilot.SuggestionsReply
}
var file_copilot_proto_depIdxs = []int32{
	3, // 0: copilot.SuggestionsReply.suggestions:type_name -> copilot.Suggestion
	0, // 1: copilot.Copilot.Run:input_type -> copilot.QueryRequest
	2, // 2: copilot.Copilot.Suggestions:input_type -> copilot.SuggestionsRequest
	1, // 3: copilot.Copilot.Run:output_type -> copilot.AnswerReply
	4, // 4: copilot.Copilot.Suggestions:output_type -> copilot.SuggestionsReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_copilot_proto_init() }
func file_copilot_proto_init() {
	if File_copilot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_copilot_proto_rawDesc), len(file_copilot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_copilot_proto_goTypes,
		DependencyIndexes: file_copilot_proto_depIdxs,
		MessageInfos:      file_copilot_proto_msgTypes,
	}.Build()
	File_copilot_proto = out.File
	file_copilot_proto_goTypes = nil
	file_copilot_proto_depIdxs = nil
}
